/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './modal.module';
export const ModalModuleNgFactory:i0.NgModuleFactory<i1.ModalModule> = i0.ɵcmf(i1.ModalModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,([] as any[])],[3,i0.ComponentFactoryResolver],i0.NgModuleRef]),i0.ɵmpd(4608,
          i1.ModalService,i1.ModalService,[i0.Compiler,i0.NgModuleRef]),i0.ɵmpd(512,
          i1.ModalModule,i1.ModalModule,([] as any[]))]);
    });
const styles_ModalPlaceholderComponent:any[] = ['.ng2-modal[_ngcontent-%COMP%] {display: block;width: 600px;max-width: 100%;height: 400px;max - height: 100%;position: fixed;z-index: 9000;left: 50 %;top: 50 %;transform: translate(-50 %, -50 %);background: white;box-shadow: 0 0 60px 10px rgba(0, 0, 0, 0.9);}',
    '.ng2[_ngcontent-%COMP%]   -[_ngcontent-%COMP%]   modal[_ngcontent-%COMP%]   -[_ngcontent-%COMP%]   content[_ngcontent-%COMP%] {position: absolute;top: 10 %;left: 0;width: 100 %;height: 100 %;overflow: auto;padding: 20px 50px 20px 20px;}',
    '.ng2[_ngcontent-%COMP%]   -[_ngcontent-%COMP%]   modal[_ngcontent-%COMP%]   -[_ngcontent-%COMP%]   overlay[_ngcontent-%COMP%] {position: fixed;top: 0;left: 0;width: 100 %;height: 100 %;z-index: 8000;background: rgba(0, 0, 0, 0.6);}'];
export const RenderType_ModalPlaceholderComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:0,
    styles:styles_ModalPlaceholderComponent,data:{}});
export function View_ModalPlaceholderComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[i0.ɵqud(402653184,1,{viewContainerRef:0}),(_l()(),i0.ɵeld(0,(null as any),
      (null as any),2,'div',[['class','ng2-modal']],(null as any),(null as any),(null as any),
      (null as any),(null as any))),(_l()(),i0.ɵeld(0,(null as any),(null as any),
      1,'div',[['class','ng2-modal-content']],(null as any),(null as any),(null as any),
      (null as any),(null as any))),(_l()(),i0.ɵeld(0,[['modalplaceholder',1]],(null as any),
      0,'div',([] as any[]),(null as any),(null as any),(null as any),(null as any),
      (null as any))),(_l()(),i0.ɵeld(0,(null as any),(null as any),0,'div',[['class',
      'ng2-modal-overlay']],(null as any),(null as any),(null as any),(null as any),
      (null as any)))],(null as any),(null as any));
}
export function View_ModalPlaceholderComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'app-root',([] as any[]),
      (null as any),(null as any),(null as any),View_ModalPlaceholderComponent_0,RenderType_ModalPlaceholderComponent)),
      i0.ɵdid(114688,(null as any),0,i1.ModalPlaceholderComponent,[i1.ModalService,
          i0.Injector],(null as any),(null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const ModalPlaceholderComponentNgFactory:i0.ComponentFactory<i1.ModalPlaceholderComponent> = i0.ɵccf('app-root',
    i1.ModalPlaceholderComponent,View_ModalPlaceholderComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovV2ViUHJvamVjdHMvbmcyLW1vZGFsLWRpYWxvZy9tb2RhbC5tb2R1bGUubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vRDovV2ViUHJvamVjdHMvbmcyLW1vZGFsLWRpYWxvZy9tb2RhbC5tb2R1bGUudHMiLCJuZzovLy9EOi9XZWJQcm9qZWN0cy9uZzItbW9kYWwtZGlhbG9nL21vZGFsLm1vZHVsZS50cy5Nb2RhbFBsYWNlaG9sZGVyQ29tcG9uZW50Lmh0bWwiLCJuZzovLy9EOi9XZWJQcm9qZWN0cy9uZzItbW9kYWwtZGlhbG9nL21vZGFsLm1vZHVsZS50cy5Nb2RhbFBsYWNlaG9sZGVyQ29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiPGRpdiBjbGFzcz0nbmcyLW1vZGFsJz48ZGl2IGNsYXNzPSduZzItbW9kYWwtY29udGVudCc+PGRpdiAjbW9kYWxwbGFjZWhvbGRlcj48L2Rpdj48L2Rpdj48L2Rpdj48ZGl2IGNsYXNzPSduZzItbW9kYWwtb3ZlcmxheSc+PC9kaXY+IiwiPGFwcC1yb290PjwvYXBwLXJvb3Q+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OERDQUE7TUFBQTtNQUFBLDhCQUF1QjtNQUFBO01BQUEsOEJBQStCO01BQUE7TUFBQSxnQkFBeUM7TUFBQTtNQUFBOzs7b0JDQS9GO01BQUE7YUFBQTtxQkFBQTtJQUFBOzs7OyJ9
