/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './modal.module';
export const ModalModuleNgFactory:i0.NgModuleFactory<i1.ModalModule> = i0.ɵcmf(i1.ModalModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,([] as any[])],[3,i0.ComponentFactoryResolver],i0.NgModuleRef]),i0.ɵmpd(4608,
          i1.ModalService,i1.ModalService,[i0.Compiler]),i0.ɵmpd(512,i1.ModalModule,
          i1.ModalModule,([] as any[]))]);
    });
const styles_ModalPlaceholderComponent:any[] = ([] as any[]);
export const RenderType_ModalPlaceholderComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_ModalPlaceholderComponent,data:{}});
export function View_ModalPlaceholderComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[i0.ɵqud(402653184,1,{viewContainerRef:0}),(_l()(),i0.ɵeld(16777216,
      [[1,3],['modalplaceholder',1]],(null as any),0,'div',([] as any[]),(null as any),
      (null as any),(null as any),(null as any),(null as any)))],(null as any),(null as any));
}
export function View_ModalPlaceholderComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'modal-placeholder',
      ([] as any[]),(null as any),(null as any),(null as any),View_ModalPlaceholderComponent_0,
      RenderType_ModalPlaceholderComponent)),i0.ɵdid(114688,(null as any),0,i1.ModalPlaceholderComponent,
      [i1.ModalService,i0.Injector],(null as any),(null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const ModalPlaceholderComponentNgFactory:i0.ComponentFactory<i1.ModalPlaceholderComponent> = i0.ɵccf('modal-placeholder',
    i1.ModalPlaceholderComponent,View_ModalPlaceholderComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovV2ViUHJvamVjdHMvbmcyLW1vZGFsLWRpYWxvZy9tb2RhbC5tb2R1bGUubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vRDovV2ViUHJvamVjdHMvbmcyLW1vZGFsLWRpYWxvZy9tb2RhbC5tb2R1bGUudHMiLCJuZzovLy9EOi9XZWJQcm9qZWN0cy9uZzItbW9kYWwtZGlhbG9nL21vZGFsLm1vZHVsZS50cy5Nb2RhbFBsYWNlaG9sZGVyQ29tcG9uZW50Lmh0bWwiLCJuZzovLy9EOi9XZWJQcm9qZWN0cy9uZzItbW9kYWwtZGlhbG9nL21vZGFsLm1vZHVsZS50cy5Nb2RhbFBsYWNlaG9sZGVyQ29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiPGRpdiAjbW9kYWxwbGFjZWhvbGRlcj48L2Rpdj4iLCI8bW9kYWwtcGxhY2Vob2xkZXI+PC9tb2RhbC1wbGFjZWhvbGRlcj4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OERDQUE7TUFBQTtNQUFBOzs7b0JDQUE7TUFBQTswQ0FBQSxVQUFBO01BQUE7SUFBQTs7OzsifQ==
